version: "3.8"

services:
  maildev:
    container_name: stockwise-maildev
    build:
      context: ./backend/
      dockerfile: mailDev.Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - ${MAIL_CLIENT_PORT}:1080
      - ${MAIL_PORT}:1025
    networks:
      - stockwise-network

  backend:
    container_name: stockwise-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - db
      - maildev
    env_file:
      - ./backend/.env
    networks:
      - stockwise-network
    restart: unless-stopped

  db:
    container_name: stockwise-db
    image: postgres:14
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - stockwise-network

networks:
  stockwise-network:

volumes:
  db:
