version: '3.8'

services:
  backend:
    container_name: stockwise-backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    depends_on:
      - db
    environment:
    - ./backend/.env
    networks:
      - stockwise-network
    
  db:
    container_name: stockwise-db
    image: postgres:14
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - stockwise-network

networks:
  stockwise-network:

volumes:
  db: