version: '3.8'

services:
  backend:
    container_name: stockwise-backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - db
    env_file:
      - ./backend/.env
    networks:
      - stockwise-network 
    restart: unless-stopped
    
  db:
    container_name: stockwise-db
    image: postgres:14
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - stockwise-network

networks:
  stockwise-network:

volumes:
  db: