/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './pages/__root';
import { Route as DashboardIndexImport } from './pages/dashboard/index';
import { Route as AuthResetImport } from './pages/auth/reset';
import { Route as AuthRegisterImport } from './pages/auth/register';
import { Route as AuthLoginImport } from './pages/auth/login';
import { Route as AuthForgotImport } from './pages/auth/forgot';

// Create/Update Routes

const DashboardIndexRoute = DashboardIndexImport.update({
	path: '/dashboard/',
	getParentRoute: () => rootRoute,
} as any);

const AuthResetRoute = AuthResetImport.update({
	path: '/auth/reset',
	getParentRoute: () => rootRoute,
} as any);

const AuthRegisterRoute = AuthRegisterImport.update({
	path: '/auth/register',
	getParentRoute: () => rootRoute,
} as any);

const AuthLoginRoute = AuthLoginImport.update({
	path: '/auth/login',
	getParentRoute: () => rootRoute,
} as any);

const AuthForgotRoute = AuthForgotImport.update({
	path: '/auth/forgot',
	getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
	interface FileRoutesByPath {
		'/auth/forgot': {
			preLoaderRoute: typeof AuthForgotImport;
			parentRoute: typeof rootRoute;
		};
		'/auth/login': {
			preLoaderRoute: typeof AuthLoginImport;
			parentRoute: typeof rootRoute;
		};
		'/auth/register': {
			preLoaderRoute: typeof AuthRegisterImport;
			parentRoute: typeof rootRoute;
		};
		'/auth/reset': {
			preLoaderRoute: typeof AuthResetImport;
			parentRoute: typeof rootRoute;
		};
		'/dashboard/': {
			preLoaderRoute: typeof DashboardIndexImport;
			parentRoute: typeof rootRoute;
		};
	}
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
	AuthForgotRoute,
	AuthLoginRoute,
	AuthRegisterRoute,
	AuthResetRoute,
	DashboardIndexRoute,
]);

/* prettier-ignore-end */
